version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: app
    path: ""
    text-resources:
      - path: src/lang/*.json
        format: simple-value-value
